config/routes.rb
require 'sidekiq/web' 
Rails.application.routes.draw do
  resources :events, only: [:index, :new, :create]
  get "events/:event_id/enroll", to: "events#enroll", as: "event_enroll"
  get "events/:event_id/unenroll", to: "events#unenroll", as: "event_unenroll"
  mount Sidekiq::Web => '/sidekiq'
  root "events#index"
  resources :employees
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord

    validates :title, :description, :event_time, presence: true
    has_many :registrations
    has_many :users, through: :registrations


end

app/models/registration.rb
class Registration < ApplicationRecord
    belongs_to :event 
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :registrations
  has_many :events, through: :registrations

  after_create  :perform_creation_jobs

  private 
  def perform_creation_jobs 
      UserJob.perform_now(self) 
      CreateEmployeeJob.set(wait: 2.minutes).perform_later(self)                    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:email)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_event, only: [:enroll, :unenroll]

    def index 
        @events = Event.all 
        @registered_events = Registration.where(user_id: current_user.id).pluck(:event_id)
    end
    
    def new 
        @event = Event.new
    end

    def create 
        @event = Event.create(event_params)

        if @event.save 
            redirect_to events_path
        else  
            render :new, status: :unprocessable_entity
        end
    end 

    def enroll 
        regi = Registration.new(event_id: @event.id)
        regi.user_id = current_user.id
        if regi.save 
            flash.now[:notice] = "Registered Successfully."
        else
            flash.now[:error] = "Can not register."
        end
        redirect_to events_path 
    end

    def unenroll 
        regi = Registration.where(event_id: @event.id, user_id: current_user.id).take
        if regi && regi.destroy 
            flash.now[:notice] = "Unenrolled successfully."
        else
            flash.now[:error] = "Can not Un-Enroll."
        end
        redirect_to events_path 
    end

    private 
    def set_event 
        @event = Event.find(params[:event_id]) 
    end

    def event_params 
        params.require(:event).permit(:title, :description, :event_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <p>
    <strong>Email:</strong>
    <%= employee.email %>
  </p>

</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Show this employee", @employee %> |
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Employees</h1>

<div id="employees">
  <% @employees.each do |employee| %>
    <%= render employee %>
    <p>
      <%= link_to "Show this employee", employee %>
    </p>
  <% end %>
</div>

<%= link_to "New employee", new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render "form", employee: @employee %>

<br>

<div>
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

<div>
  <%= link_to "Edit this employee", edit_employee_path(@employee) %> |
  <%= link_to "Back to employees", employees_path %>

  <%= button_to "Destroy this employee", @employee, method: :delete %>
</div>

app/views/events/index.html.erb
<div class="container">
<table class="table">
  <thead>
    <tr>
      <th scope="col">#id</th>
      <th scope="col">event Name</th>
      <th scope="col">Description</th>
      <th scope="col">Date</th>      
    </tr>
  </thead>
  <tbody>
  <% @events.each do |event|%>
    <tr>
      <th scope="row"><%= event.id %></th>
      <td><%= event.title %></td>
      <td><%= event.description %></td>
      <td><%= event.event_time %></td>
      <% if ! event.id.in?(@registered_events)%>
      <td><%= link_to "Enroll  ", event_enroll_path(event.id), class: "btn btn-primary" %></td>
      <% else %>
      <td><%= link_to "Deroll", event_unenroll_path(event.id), class: "btn btn-danger" %></td>
      <% end %>
    </tr>
  <%end %>

  </tbody>
</table>
</div>

app/views/events/new.html.erb
<div class="container">
    <%=  form_with(url: events_path, model: @event, method: :post ) do |form| %>

    <div class="row">  
      <div class="col-4">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control" %>
        </div>
    </div>
    <br>
    
    <div class="row">  
      <div class="col-4">
        <%= form.label :event_time %>
        <%= form.datetime_field :event_time,  class: "form-control" %>
    </div>
    </div>
    <br>
    <div class="row">  
      <div class="col-4">
        <%= form.label :description %>
        <%= form.text_field :description,  class: "form-control" %>
    </div>
    </div>
    
    
    <%= form.submit class: "btn btn-primary " %>
    <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AtiveJobPractical</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/events">Events</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/events/new">Create Event</a>
        </li>
        
        <li class="nav-item active">
          <a class="nav-link"  href="/events/show">My Events</a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="/events/show">Enrolled Events</a>
        </li>


        <li class="nav-item active">
          <a class="nav-link" href="/employees">Employees</a>
        </li>
    


        <% if user_signed_in? %>
        <li class = "nav-item active">	
          <p> Logged in as <strong><%= current_user.email %> </strong></p>
        </li>
        <li class="nav-item active">
          <%= button_to "Edit profile", edit_user_registration_path, class: "btn btn-secondary navbar-btn " %> 
        </li>
        <li class="nav-item active">
          <%= button_to "Sign out", destroy_user_session_path, class: "btn btn-outline-danger sign-out-btn navbar-btn" , :method => :delete %>
        </li>
        <% else %>
        <li class="nav-tem active">
          <%= link_to "Sign up", new_user_registration_path, class: "navbar-link"  %> |
          <%= link_to "Login", new_user_session_path, class: "navbar-link"  %>
        </li>
        <% end %>
    </ul>
  </nav>
    <%= yield %>
  </body>
</html>